In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Concatenate FIFA Files

In [2]:
df21 = pd.read_csv(r'data\FIFA21_official_data.csv')
df22 = pd.read_csv(r'data\FIFA22_official_data.csv')
df23 = pd.read_csv(r'data\FIFA23_official_data.csv')

In [3]:
for i, col in enumerate(df21.columns):
  if col not in df23.columns:
    print(f"{i+1}- {col}")

22- Jersey Number
28- Crossing
29- Finishing
30- HeadingAccuracy
31- ShortPassing
32- Volleys
33- Dribbling
34- Curve
35- FKAccuracy
36- LongPassing
37- BallControl
38- Acceleration
39- SprintSpeed
40- Agility
41- Reactions
42- Balance
43- ShotPower
44- Jumping
45- Stamina
46- Strength
47- LongShots
48- Aggression
49- Interceptions
50- Positioning
51- Vision
52- Penalties
53- Composure
54- Marking
55- StandingTackle
56- SlidingTackle
57- GKDiving
58- GKHandling
59- GKKicking
60- GKPositioning
61- GKReflexes
62- Best Position
65- DefensiveAwareness

In [4]:
print(df21.shape)
print(df22.shape)
print(df23.shape)

(17108, 65)
(16710, 65)
(17660, 29)

In [5]:
df = pd.concat([df21, df22, df23])
df.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,Release Clause,DefensiveAwareness,Kit Number
0,176580,L. Suárez,33,https://cdn.sofifa.com/players/176/580/20_60.png,Uruguay,https://cdn.sofifa.com/flags/uy.png,87,87,Atlético Madrid,https://cdn.sofifa.com/teams/240/light_30.png,...,27.0,25.0,31.0,33.0,37.0,ST,87.0,€64.6M,57.0,NaN
1,192985,K. De Bruyne,29,https://cdn.sofifa.com/players/192/985/20_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,91,91,Manchester City,https://cdn.sofifa.com/teams/10/light_30.png,...,15.0,13.0,5.0,10.0,13.0,CAM,91.0,€161M,68.0,NaN
2,212198,Bruno Fernandes,25,https://cdn.sofifa.com/players/212/198/20_60.png,Portugal,https://cdn.sofifa.com/flags/pt.png,87,90,Manchester United,https://cdn.sofifa.com/teams/11/light_30.png,...,12.0,14.0,15.0,8.0,14.0,CAM,88.0,€124.4M,72.0,NaN
3,194765,A. Griezmann,29,https://cdn.sofifa.com/players/194/765/20_60.png,France,https://cdn.sofifa.com/flags/fr.png,87,87,FC Barcelona,https://cdn.sofifa.com/teams/241/light_30.png,...,14.0,8.0,14.0,13.0,14.0,ST,87.0,€103.5M,59.0,NaN
4,224334,M. Acuña,28,https://cdn.sofifa.com/players/224/334/20_60.png,Argentina,https://cdn.sofifa.com/flags/ar.png,83,83,Sevilla FC,https://cdn.sofifa.com/teams/481/light_30.png,...,8.0,14.0,13.0,13.0,14.0,LB,83.0,€46.2M,79.0,NaN

In [6]:
df.shape

(51478, 66)

In [7]:
# Drop columns that are not needed
cols_to_drop = ['Crossing', 'Finishing', 'HeadingAccuracy',
  'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy',
  'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility',
  'Reactions', 'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength',
  'LongShots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
  'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle',
  'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
  'Best Position', 'Best Overall Rating', 'DefensiveAwareness']
df.drop(columns=cols_to_drop, inplace=True)

In [16]:
df.head()

,Row ID,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Best Overall Rating,Release Clause,DefensiveAwareness,Kit Number
0,1_FIFA21,176580,L. Suárez,33,https://cdn.sofifa.com/players/176/580/20_60.png,Uruguay,https://cdn.sofifa.com/flags/uy.png,87,87,Atlético Madrid,...,9.0,2020-09-25,NaN,2022.0,6'0,190lbs,87.0,64.6M,57.0,NaN
1,2_FIFA21,192985,K. De Bruyne,29,https://cdn.sofifa.com/players/192/985/20_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,91,91,Manchester City,...,17.0,2015-08-30,NaN,2023.0,5'11,154lbs,91.0,161M,68.0,NaN
2,3_FIFA21,212198,Bruno Fernandes,25,https://cdn.sofifa.com/players/212/198/20_60.png,Portugal,https://cdn.sofifa.com/flags/pt.png,87,90,Manchester United,...,18.0,2020-01-30,NaN,2025.0,5'10,152lbs,88.0,124.4M,72.0,NaN
3,4_FIFA21,194765,A. Griezmann,29,https://cdn.sofifa.com/players/194/765/20_60.png,France,https://cdn.sofifa.com/flags/fr.png,87,87,FC Barcelona,...,7.0,2019-07-12,NaN,2024.0,5'9,161lbs,87.0,103.5M,59.0,NaN
4,5_FIFA21,224334,M. Acuña,28,https://cdn.sofifa.com/players/224/334/20_60.png,Argentina,https://cdn.sofifa.com/flags/ar.png,83,83,Sevilla FC,...,19.0,2020-09-14,NaN,2024.0,5'8,152lbs,83.0,46.2M,79.0,NaN

In [8]:
# df.to_excel("fifa_concatenated.xlsx", index=False)

In [9]:
df = pd.read_excel("fifa_concatenated.xlsx", sheet_name=1)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46949 entries, 0 to 46948
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Row ID                    46949 non-null  object
 1   ID                        46949 non-null  int64
 2   Name                      46949 non-null  object
 3   Age                       46949 non-null  int64
 4   Photo                     46949 non-null  object
 5   Nationality               46949 non-null  object
 6   Flag                      46949 non-null  object
 7   Overall                   46949 non-null  int64
 8   Potential                 46949 non-null  int64
 9   Club                      46949 non-null  object
 10  Club Logo                 46949 non-null  object
 11  Value (Euro)              46949 non-null  object
 12  Wage (Euro)               46949 non-null  object
 13  Special                   46949 non-null  int64
 14  Preferred Foot            46949 non-null  object
 15  International Reputation  46949 non-null  int64
 16  Weak Foot                 46949 non-null  int64
 17  Skill Moves               46949 non-null  int64
 18  Work Rate                 46949 non-null  object
 19  Body Type                 46949 non-null  object
 20  Real Face                 46949 non-null  object
 21  Position                  46948 non-null  object
 22  Jersey Number             30440 non-null  float64
 23  Joined                    46560 non-null  datetime64[ns]
 24  Loaned From               0 non-null      float64
 25  Contract Valid Until      46560 non-null  float64
 26  Height                    46949 non-null  object
 27  Weight                    46949 non-null  object
 28  Best Overall Rating       30440 non-null  float64
 29  Release Clause            46949 non-null  object
 30  DefensiveAwareness        29484 non-null  float64
 31  Kit Number                16508 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(8), object(17)
memory usage: 11.5+ MB

In [11]:
df.dropna(subset="Release Clause", inplace=True)
df.shape

(46949, 32)

In [12]:
# Remove leading/tail spaces
df['Name'] = df['Name'].apply(lambda x: x.strip())

In [ ]:
# Remove jersey numbers from player names
import re

for i, name in enumerate(df.loc[:, 'Name']):
  if re.findall(r'^\s*[0-9]+', df.iloc[i, 2]):
    print(f"{i+1}) '{df.iloc[i, 2]}' -> '{df.iloc[i, 2][3:]}'")
    df.iloc[i, 2] = df.iloc[i, 2][3:]

In [14]:
# df.to_excel("fifa_concatenated.xlsx", index=False, sheet_name='Cleaned Data')

### ☑️ Units Standardization (Kg, lbs, ', Cm)

In [33]:
df = pd.read_excel("fifa_concatenated.xlsx", sheet_name='Working Sheet')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46949 entries, 0 to 46948
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Row ID                    46949 non-null  object
 1   ID                        46949 non-null  int64
 2   Name                      46949 non-null  object
 3   Age                       46949 non-null  int64
 4   Photo                     46949 non-null  object
 5   Nationality               46949 non-null  object
 6   Flag                      46949 non-null  object
 7   Overall                   46949 non-null  int64
 8   Potential                 46949 non-null  int64
 9   Club                      46949 non-null  object
 10  Club Logo                 46949 non-null  object
 11  Value (Euro)              46949 non-null  object
 12  Wage (Euro)               46949 non-null  object
 13  Special                   46949 non-null  int64
 14  Preferred Foot            46949 non-null  object
 15  International Reputation  46949 non-null  int64
 16  Weak Foot                 46949 non-null  int64
 17  Skill Moves               46949 non-null  int64
 18  Work Rate                 46949 non-null  object
 19  Body Type                 46949 non-null  object
 20  Real Face                 46949 non-null  object
 21  Position                  46948 non-null  object
 22  Jersey Number             30440 non-null  float64
 23  Joined                    46560 non-null  datetime64[ns]
 24  Loaned From               0 non-null      float64
 25  Contract Valid Until      46560 non-null  float64
 26  Height                    46949 non-null  object
 27  Weight                    46949 non-null  object
 28  Best Overall Rating       30440 non-null  float64
 29  Release Clause            46949 non-null  object
 30  DefensiveAwareness        29484 non-null  float64
 31  Kit Number                16508 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(8), object(17)
memory usage: 11.5+ MB

In [ ]:
# Normalize 'Release Clause' column
df['Release Clause (Normalized)'] = ""
for i in range(df.shape[0]):
  if not pd.isnull(df.loc[i, 'Release Clause']):
    if df.iloc[i]['Release Clause'][-1] == "M":
      df.loc[i, 'Release Clause (Normalized)'] = float(df.iloc[i]['Release Clause'][1:-1]) * 1000000
    elif df.iloc[i]['Release Clause'][-1] == "K":
      df.loc[i, 'Release Clause (Normalized)'] = float(df.iloc[i]['Release Clause'][1:-1]) * 1000
    else:
      TypeError("Unknown format")
  else:
    df.loc[i, 'Release Clause (Normalized)'] = np.nan

# df['Release Clause (Normalized)'].astype('int')

In [34]:
# Normalize 'Weight/ Height' columns
for i in range(df.shape[0]):
  if not pd.isnull(df.loc[i, "Weight"]):
    if df.loc[i, "Weight"][-3:] == "lbs":
      df.loc[i, "Weight"] = int(int(df.loc[i, "Weight"][:-3]) * 0.453592)
    elif df.loc[i, "Weight"][-2:] == "kg":
      df.loc[i, "Weight"] = int(df.loc[i, "Weight"][:-2])

df.tail()

,Row ID,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Best Overall Rating,Release Clause,DefensiveAwareness,Kit Number
46944,17656_FIFA23,269526,Deng Xiongtao,19,https://cdn.sofifa.net/players/269/526/23_60.png,China PR,https://cdn.sofifa.net/flags/cn.png,48,61,Meizhou Hakka,...,NaN,2022-04-11,NaN,2027.0,190cm,78,NaN,218K,NaN,35.0
46945,17657_FIFA23,267946,Lim Jun Sub,17,https://cdn.sofifa.net/players/267/946/22_60.png,Korea Republic,https://cdn.sofifa.net/flags/kr.png,48,64,Jeju United FC,...,NaN,2022-01-01,NaN,2026.0,195cm,84,NaN,188K,NaN,21.0
46946,17658_FIFA23,270567,A. Demir,25,https://cdn.sofifa.net/players/270/567/23_60.png,Turkey,https://cdn.sofifa.net/flags/tr.png,51,56,Ümraniyespor,...,NaN,2021-06-06,NaN,2023.0,190cm,82,NaN,142K,NaN,12.0
46947,17659_FIFA23,256624,S. Czajor,18,https://cdn.sofifa.net/players/256/624/21_60.png,Poland,https://cdn.sofifa.net/flags/pl.png,50,65,Fleetwood Town,...,NaN,2020-01-01,NaN,2021.0,187cm,79,NaN,214K,NaN,40.0
46948,17660_FIFA23,256376,F. Jakobsson,20,https://cdn.sofifa.net/players/256/376/21_60.png,Sweden,https://cdn.sofifa.net/flags/se.png,50,61,IFK Norrköping,...,NaN,2020-01-08,NaN,2021.0,186cm,78,NaN,131K,NaN,30.0

In [37]:
df.rename(columns={'Weight': 'Weight (KG)'}, inplace=True)